# Generated by Django 3.1 on 2020-08-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200825_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AlterField(
            model_name='product',
            name='desciption',
            field=models.TextField(max_length=1028, null=True),
        ),
    ]
