# Generated by Django 3.1 on 2020-09-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200901_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='product/'),
        ),
    ]
